//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhieuThue()
        {
            this.PhieuTra = new HashSet<PhieuTra>();
        }
    
        public int maCTPhieuThue { get; set; }
        public int maDia { get; set; }
        public int maPhieuThue { get; set; }
        public Nullable<System.DateTime> hanTra { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual Dia Dia { get; set; }
        public virtual PhieuThue PhieuThue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuTra> PhieuTra { get; set; }
    }
}
