//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int maNhanVien { get; set; }
        public int maTaiKhoan { get; set; }
        public string hoTen { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
