//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThue()
        {
            this.ChiTietPhieuThue = new HashSet<ChiTietPhieuThue>();
        }
    
        public int maPhieuThue { get; set; }
        public int maKhachHang { get; set; }
        public Nullable<double> tienCoc { get; set; }
        public Nullable<System.DateTime> ngayThue { get; set; }
        public Nullable<bool> trangThaiTraPhiTre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuThue> ChiTietPhieuThue { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
