//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuaDe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuaDe()
        {
            this.Dia = new HashSet<Dia>();
        }
    
        public int maTuaDe { get; set; }
        public string tenTuaDe { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> donGia { get; set; }
        public string moTa { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> ngayChoThue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dia> Dia { get; set; }
    }
}
